# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jemoji


# SCSS
sass:
  style: :compressed

# Permalinks
permalink: pretty

jekyll-mentions: https://twitter.com

# Site info
url: "http://darn.es"
title: "David Darnes"
name: "David Darnes"
description: "Web Designer & Front-end Developer"
logo: "https://avatars1.githubusercontent.com/u/1177460?s=300"

# SEO > twitter name meta
twitter:
  username: DavidDarnes

# SEO > site alias meta
social:
  links:
    - https://twitter.com/DavidDarnes
    - https://www.facebook.com/daviddarnes
    - https://www.linkedin.com/in/daviddarnes
    - https://plus.google.com/+DavidDarnes
    - https://github.com/DavidDarnes

# SEO > author meta
author: DavidDarnes
